jwt.expiration=3600
# =========================================
# APPLICATION
# =========================================

quarkus.application.name=jusconnect-platform
quarkus.http.port=8080

# =========================================
# DATABASE
# =========================================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

# =========================================
# SWAGGER / OPENAPI
# =========================================

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/q/openapi

# =========================================
# JWT
# =========================================

mp.jwt.verify.issuer=jusconnect

# smallrye.jwt.sign.key.location=privateKey.pem
# mp.jwt.verify.publickey.location=publicKey.pem

security.jwt-secret=jusconnect-secret-key
security.jwt-expiration=86400
security.issuer=jusconnect

# =========================================
# LOGGING
# =========================================

quarkus.log.level=INFO

# =========================================
# REDIS
# =========================================

quarkus.redis.hosts=redis://localhost:6379

# =========================================
# REST CLIENTS
# =========================================

quarkus.rest-client.ai-service.url=http://localhost:9001
quarkus.rest-client.notification-service.url=http://localhost:9002
quarkus.rest-client.chat-service.url=http://localhost:9003