# =========================================
# DEV PROFILE
# =========================================

quarkus.hibernate-orm.log.sql=true

quarkus.log.console.level=DEBUG

quarkus.live-reload.instrumentation=true

quarkus.datasource.devservices.enabled=true

quarkus.redis.devservices.enabled=true