apiVersion: apps/v1
kind: Deployment
metadata:
  name: jusconnect
  namespace: jusconnect
  labels:
    app: jusconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jusconnect
  template:
    metadata:
      labels:
        app: jusconnect
    spec:
      containers:
        - name: jusconnect
          image: jusconnect-platform:1.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres:5432/jusconnect"

            - name: QUARKUS_DATASOURCE_USERNAME
              value: jusconnect

            - name: QUARKUS_DATASOURCE_PASSWORD
              value: jusconnect