name: CI - JusConnect

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # Checkout
      # ==========================================
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==========================================
      # Java 17
      # ==========================================
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # ==========================================
      # Permissão Maven Wrapper
      # ==========================================
      - name: Grant execute permission
        run: chmod +x mvnw

      # ==========================================
      # Testes
      # ==========================================
      - name: Run Tests
        run: ./mvnw test

      # ==========================================
      # Build Quarkus
      # ==========================================
      - name: Build Project
        run: ./mvnw clean package -DskipTests

      # ==========================================
      # Build Docker Runtime Only
      # ==========================================
      - name: Build Docker Image
        run: docker build --no-cache -t jusconnect-platform .
